[fmt]
line_length = 120
tab_width = 2
bracket_spacing = false
int_types = 'long'
quote_style = 'single'
number_underscore = 'thousands'
multiline_func_header = 'params_first_multi'
sort_imports = true

[profile.default]
rpc_url = "https://sepolia.infura.io/v3/2b851038fbe5448e8f32586b018efc71"
solc_version = '0.8.26'
libs = ['node_modules', 'lib']
optimizer_runs = 10_000

[profile.optimized]
via_ir = true
out = 'out-via-ir'

[profile.test]
via_ir = true
out = 'out-via-ir'

[profile.docs]
src = 'src/interfaces/'

[fuzz]
runs = 1000



[etherscan]
sepolia = { key = "UJIP5DSFUUA7BMCHH9GU67WN574PCY4N59", chain = "sepolia" }